# Generated by Django 5.1.3 on 2024-11-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiongen',
            name='category',
        ),
        migrations.AddField(
            model_name='fullstudentanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.DeleteModel(
            name='OptionGen',
        ),
        migrations.DeleteModel(
            name='QuestionGen',
        ),
    ]
