# Generated by Django 5.1.3 on 2025-04-19 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_questiongen_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('NORMAL', 'Bài kiểm tra thông thường'), ('PDF', 'Bài kiểm tra PDF')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='PDFSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submission_file', models.FileField(upload_to='quiz_submissions/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('is_graded', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
                ('quiz_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
